name = "cbv_fe"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.dev]
name = "cbv_fe-dev"
pages_build_output_dir = "dist"

[env.staging]
name = "cbv_fe-staging"
pages_build_output_dir = "dist"

[env.prod]
name = "cbv_fe-prod"
pages_build_output_dir = "dist"
